### ISSUE TITLE
Deploy scripts for Histograph

### ISSUE THREAD

**Issue by bertspaan** [histograph/deploy#1]
This repository should contain deploy scripts which will deploy Histograph to erfgeo.nl (or to any other, configurable, server). See if it's useful to try and use [Docker](https://www.docker.com/).

Histograph currently consists of the following subprojects/repositories:
- [Histograph API](https://github.com/erfgoed-en-locatie/histograph) - Node.js search API
- [Histograph Core](https://github.com/erfgoed-en-locatie/histograph-core) - Message queue processor & reasoning engine
- [Histograph IO](https://github.com/erfgoed-en-locatie/histograph-io) - Data import API

Moved from erfgoed-en-locatie/histograph#11.

Tasks:
- [x] Select docker image for application deployment
- [x] Compile list of commands, commit
- [x] Create docker file and commit to histograph-deploy repository

**Comment by reinvantveer** [comment]
First working version, builds image of basic stack components.
